#include "HOOK/keyboard_event.h"

const char* SDLKeycodeToString(SDL_Keycode code)
{
	switch (code)
	{
	case SDLK_KP_ENTER:
	case SDLK_RETURN:
		return "Return";
	case SDLK_ESCAPE:
		return "Escape";
	case SDLK_BACKSPACE:
		return "Backspace";
	case SDLK_TAB:
		return "Tab";
	case SDLK_SPACE:
		return "Space";
	case SDLK_EXCLAIM:
		return "!";
	case SDLK_QUOTEDBL:
		return "\"";
	case SDLK_HASH:
		return "#";
	case SDLK_PERCENT:
		return "%";
	case SDLK_DOLLAR:
		return "$";
	case SDLK_AMPERSAND:
		return "&";
	case SDLK_QUOTE:
		return "'";
	case SDLK_LEFTPAREN:
		return "(";
	case SDLK_RIGHTPAREN:
		return ")";
	case SDLK_ASTERISK:
		return "*";
	case SDLK_PLUS:
		return "+";
	case SDLK_COMMA:
		return ",";
	case SDLK_MINUS:
		return "-";
	case SDLK_PERIOD:
		return ".";
	case SDLK_SLASH:
		return "/";
	case SDLK_0:
		return "0";
	case SDLK_1:
		return "1";
	case SDLK_2:
		return "2";
	case SDLK_3:
		return "3";
	case SDLK_4:
		return "4";
	case SDLK_5:
		return "5";
	case SDLK_6:
		return "6";
	case SDLK_7:
		return "7";
	case SDLK_8:
		return "8";
	case SDLK_9:
		return "9";
	case SDLK_COLON:
		return ":";
	case SDLK_SEMICOLON:
		return ";";
	case SDLK_LESS:
		return "<";
	case SDLK_EQUALS:
		return "=";
	case SDLK_GREATER:
		return ">";
	case SDLK_QUESTION:
		return "?";
	case SDLK_AT:
		return "@";
	case SDLK_LEFTBRACKET:
		return "[";
	case SDLK_BACKSLASH :
		return "\\";
	case SDLK_RIGHTBRACKET:
		return "]";
	case SDLK_CARET:
		return "^";
	case SDLK_UNDERSCORE:
		return "_";
	case SDLK_BACKQUOTE:
		return "`";
	case SDLK_a:
		return "A";
	case SDLK_b:
		return "B";
	case SDLK_c:
		return "C";
	case SDLK_d:
		return "D";
	case SDLK_e:
		return "E";
	case SDLK_f:
		return "F";
	case SDLK_g:
		return "G";
	case SDLK_h:
		return "H";
	case SDLK_i:
		return "I";
	case SDLK_j:
		return "J";
	case SDLK_k:
		return "K";
	case SDLK_l:
		return "L";
	case SDLK_m:
		return "M";
	case SDLK_n:
		return "N";
	case SDLK_o:
		return "O";
	case SDLK_p:
		return "P";
	case SDLK_q:
		return "Q";
	case SDLK_r:
		return "R";
	case SDLK_s:
		return "S";
	case SDLK_t:
		return "T";
	case SDLK_u:
		return "U";
	case SDLK_v:
		return "V";
	case SDLK_w:
		return "W";
	case SDLK_x:
		return "X";
	case SDLK_y:
		return "Y";
	case SDLK_z:
		return "Z";
	case SDLK_CAPSLOCK:
		return "Capslock";
	case SDLK_F1:
		return "F1";
	case SDLK_F2:
		return "F2";
	case SDLK_F3:
		return "F3";
	case SDLK_F4:
		return "F4";
	case SDLK_F5:
		return "F5";
	case SDLK_F6:
		return "F6";
	case SDLK_F7:
		return "F7";
	case SDLK_F8:
		return "F8";
	case SDLK_F9:
		return "F9";
	case SDLK_F10:
		return "F10";
	case SDLK_F11:
		return "F11";
	case SDLK_F12:
		return "F12";
	case SDLK_F13:
		return "F13";
	case SDLK_F14:
		return "F14";
	case SDLK_F15:
		return "F15";
	case SDLK_F16:
		return "F16";
	case SDLK_F17:
		return "F17";
	case SDLK_F18:
		return "F18";
	case SDLK_F19:
		return "F19";
	case SDLK_F20:
		return "F20";
	case SDLK_F21:
		return "F21";
	case SDLK_F22:
		return "F22";
	case SDLK_F23:
		return "F23";
	case SDLK_F24:
		return "F24";
	case SDLK_PRINTSCREEN:
		return "PrintScreen";
	case SDLK_SCROLLLOCK:
		return "Scrolllock";
	//case SDLK_PAUSE:
	//	return "MediaPlayPause";
	case SDLK_INSERT:
		return "Insert";
	case SDLK_HOME:
		return "Home ";
	case SDLK_PAGEUP:
		return "PageUp ";
	case SDLK_DELETE:
		return "Delete";
	case SDLK_END:
		return "End";
	case SDLK_PAGEDOWN:
		return "PageDown";
	case SDLK_RIGHT:
		return "Right";
	case SDLK_LEFT:
		return "Left ";
	case SDLK_DOWN:
		return "Down";
	case SDLK_UP:
		return "Up";
	case SDLK_NUMLOCKCLEAR:
		return "Numlock";
	case SDLK_KP_DIVIDE:
		return "numdiv";
	case SDLK_KP_MULTIPLY:
		return "nummult";
	case SDLK_KP_MINUS:
		return "numsub";
	case SDLK_KP_PLUS:
		return "numadd";
	case SDLK_KP_PERIOD:
		return "numdec";
	case SDLK_KP_1:
		return "num1";
	case SDLK_KP_2:
		return "num2";
	case SDLK_KP_3:
		return "num3";
	case SDLK_KP_4:
		return "num4";
	case SDLK_KP_5:
		return "num5";
	case SDLK_KP_6:
		return "num6";
	case SDLK_KP_7:
		return "num7";
	case SDLK_KP_8:
		return "num8";
	case SDLK_KP_9:
		return "num9";
	case SDLK_KP_0:
		return "num0";
	case SDLK_VOLUMEUP:
		return "VolumeUp";
	case SDLK_VOLUMEDOWN:
		return "VolumeDown ";
	case SDLK_MUTE:
		return "VolumeMute";
	case SDLK_AUDIONEXT:
		return "MediaNextTrack";
	case SDLK_AUDIOPREV:
		return "MediaPreviousTrack";
	case SDLK_AUDIOSTOP:
		return "MediaStop";
	case SDLK_AUDIOPLAY:
		return "MediaPlayPause";
	//case SDLK_AUDIOMUTE:


	case SDLK_LCTRL:
	case SDLK_RCTRL:
		return "Control";
	case SDLK_LSHIFT:
	case SDLK_RSHIFT:
		return "Shift";
	case SDLK_LALT:
	case SDLK_RALT:
		return "Alt";
	case SDLK_LGUI:
	case SDLK_RGUI:
		return "Super";
	};
	return NULL;
}
